spring.application.name=Backend

spring.datasource.url=jdbc:mysql://localhost:3306/EmployeeManagementSystem
spring.datasource.username=root
spring.datasource.password=saikat123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#=============JWT Variables===========================

jwt.secret=MyVeryStrongSecretKeyForJWTAuthentication2026SecureKey123

jwt.access.expiration=900000
jwt.refresh.expiration=604800000

jwt.header=Authorization
jwt.token-prefix=Bearer

jwt.cookie.name=refreshToken
jwt.cookie.http-only=true
jwt.cookie.secure=false
jwt.cookie.max-age=604800


#================MAIL Related========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codingsaikat@gmail.com
spring.mail.password=pmisswuiwmrbmrnj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true