package com.ems.enums;

public enum LeaveType {

    SICK_LEAVE,
    CASUAL_LEAVE,
    ANNUAL_LEAVE,
    PAID_LEAVE,
    UNPAID_LEAVE,
    MATERNITY_LEAVE,
    PATERNITY_LEAVE,
    BEREAVEMENT_LEAVE,
    STUDY_LEAVE,
    COMPENSATORY_LEAVE

}