package com.ems.enums;

public enum LeaveCategory {

    SICK_LEAVE,
    CASUAL_LEAVE,
    ANNUAL_LEAVE,
    PAID_LEAVE,
    UNPAID_LEAVE,
    MATERNITY_LEAVE,
    PATERNITY_LEAVE,
    EMERGENCY_LEAVE,
    COMPENSATORY_LEAVE,
    STUDY_LEAVE,
    WORK_FROM_HOME

}